### PR TITLE
added the MIT license

### PR DESCRIPTION
**Pull request by enigmastrat**
@pietern Would you consider releasing this source under an MIT License? If so, I've added it to this branch for merging. If not MIT, another open source license possibly? I've enjoyed toying around with this source over the last few days and would love to keep contributing.

Thanks!

### CODE REVIEW

**Comment by pietern** [comment]
For sure! As far as I'm concerned this can be under the "do whatever you want" license :+1: 

Fun to hear you found the code useful and have been using it. I'd be keen to see some sample images if you can share any. Thanks for sending the PR.

**Comment by enigmastrat** [comment]
Awesome, thanks. I created a separate branch for the false-color work I've been doing. Currently, it's a bit experimental and simple. But the results seem promising. The image here was a WAV I found online. I'm working on improving my own radio setup for results like the one below.

Near visible IR:
gooda

IR:
goodb

False-color
goodf

**Comment by martinber** [comment]
@enigmastrat That false color image was generated using your fork? If you keep the MIT license I'm going to be interested on translating your work to [my GPLv3 decoder in Rust](https://github.com/martinber/noaa-apt).

If you are looking for information about generating false color images I have no idea on how to do that. I know that [this GPLv2 decoder](https://github.com/csete/aptdec/releases/tag/v1.7) does some basic false color. Also that [this PDF has useful information](https://noaasis.noaa.gov/NOAASIS/pubs/Users_Guide-Building_Receive_Stations_March_2009.pdf). Also I think there are different ways of generating false color images: ZA, MCIR, HVC, HVCT

**Comment by enigmastrat** [comment]
@martinber Yes, the false color image came from my fork, under the false_color branch. It is very experimental at the moment. Admittedly, I have a really basic understanding of false color generation. Currently, the values are all hard coded, where they probably need to be calibrated to the particular capture and/or configurable. When trying the image formation and false color application on some of my low quality captures, it was an utter failure. My goal here was to go at it a bit blind and see how I could combine these two IR wavelengths into something else. My next step is to look into some of the established methods you included.

That all being said, you are more than welcome to use it in any way you see fit.

**Comment by pietern** [comment]
Nice work @enigmastrat!!

If you want to make the false color palette configurable, you can use a lookup table instead of hard coded formulas. With a 2 dimensional lookup table (one for the visual channel and one for the IR channel) that maps both values (e.g. from 0-255) to an RGB value. Then you only have to generate a new table and you can use it with the same binary. This is what I have used in https://github.com/pietern/goestools as well, and I know others use this approach as well.

**Pull request merged**
